import "./globals.css";
import { Space_Mono } from "next/font/google";

const spaceMono = Space_Mono({
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "auto",
});

export const metadata = {
  title: "Server Actions in Next JS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={spaceMono.className}>
        <h1 className="text-3xl p-[1rem] text-center font-bold">
          Server Actions in Next JS
        </h1>
        {children}
      </body>
    </html>
  );
}
